# Generated by Django 4.1 on 2022-10-04 22:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
