# Generated by Django 4.1 on 2022-10-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0005_alter_image_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
